version: '3.7'

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users_database
